service: api-gateway

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  versionFunctions: false
  deploymentBucket: zadif-sls-deployments

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0

functions:
  graphql:
    handler: lambda.graphql
    events:
      - http:
          path: /
          method: post
          cors: true
      - http:
          path: /
          method: get
          cors: true
