service: api-gateway

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  stage: dev
  versionFunctions: false
  deploymentBucket: zadif-sls-deployments

plugins:
  # - serverless-offline
  - serverless-domain-manager

functions:
  graphql:
    handler: lambda.graphql
    events:
      - http:
          path: /
          method: post
          cors:
            origins:
              - https://api.zadif.com
      - http:
          path: /
          method: get
          cors:
            origins:
              - https://api.zadif.com

custom:
  customDomain:
    domainName: api.zadif.com
    basePath: users
    stage: dev
